/**
 * Complete Periodic Table Data — All 118 Elements
 * 
 * Sources: IUPAC, NIST, Los Alamos National Laboratory
 * Atomic masses use standard atomic weights (2021 IUPAC values)
 * Values in parentheses indicate mass number of most stable isotope
 * 
 * Grid positions use standard 18-column layout:
 *   row: period (1–7), plus 8–9 for lanthanides/actinides
 *   col: group (1–18)
 */

const CATEGORIES = {
  'alkali-metal':        { label: 'Alkali Metal',        color: '#ff6b6b' },
  'alkaline-earth-metal':{ label: 'Alkaline Earth Metal', color: '#ffa06b' },
  'transition-metal':    { label: 'Transition Metal',     color: '#ffd76b' },
  'post-transition-metal':{ label: 'Post-Transition Metal', color: '#98d8c8' },
  'metalloid':           { label: 'Metalloid',            color: '#7bc8f6' },
  'nonmetal':            { label: 'Nonmetal',             color: '#77dd77' },
  'halogen':             { label: 'Halogen',              color: '#b19cd9' },
  'noble-gas':           { label: 'Noble Gas',            color: '#c3b1e1' },
  'lanthanide':          { label: 'Lanthanide',           color: '#f0b27a' },
  'actinide':            { label: 'Actinide',             color: '#f0e68c' },
  'unknown':             { label: 'Unknown',              color: '#cccccc' },
};

const ELEMENTS = [
  // ═══════════════════════ Period 1 ═══════════════════════
  {
    number: 1, symbol: 'H', name: 'Hydrogen',
    mass: 1.008, category: 'nonmetal',
    row: 1, col: 1,
    electronConfig: '1s¹',
    electronegativity: 2.20,
    density: 0.00008988, // g/cm³
    meltingPoint: -259.16, // °C
    boilingPoint: -252.87,
    yearDiscovered: 1766,
    discoveredBy: 'Henry Cavendish',
    phase: 'Gas',
    shells: [1],
    summary: 'Hydrogen is the lightest and most abundant element in the universe, making up about 75% of all normal matter by mass. It is a colorless, odorless, highly combustible diatomic gas.',
    funFact: 'The Sun fuses about 600 million tons of hydrogen into helium every second.'
  },
  {
    number: 2, symbol: 'He', name: 'Helium',
    mass: 4.0026, category: 'noble-gas',
    row: 1, col: 18,
    electronConfig: '1s²',
    electronegativity: null,
    density: 0.0001785,
    meltingPoint: -272.20,
    boilingPoint: -268.93,
    yearDiscovered: 1868,
    discoveredBy: 'Pierre Janssen',
    phase: 'Gas',
    shells: [2],
    summary: 'Helium is the second lightest and second most abundant element in the observable universe. It is a colorless, odorless, tasteless, non-toxic, inert monatomic gas.',
    funFact: 'Helium is the only element that cannot be solidified by sufficient cooling at normal atmospheric pressure.'
  },
  // ═══════════════════════ Period 2 ═══════════════════════
  {
    number: 3, symbol: 'Li', name: 'Lithium',
    mass: 6.941, category: 'alkali-metal',
    row: 2, col: 1,
    electronConfig: '[He] 2s¹',
    electronegativity: 0.98,
    density: 0.534,
    meltingPoint: 180.54,
    boilingPoint: 1342,
    yearDiscovered: 1817,
    discoveredBy: 'Johan August Arfwedson',
    phase: 'Solid',
    shells: [2, 1],
    summary: 'Lithium is a soft, silvery-white alkali metal. It is the lightest metal and the lightest solid element under standard conditions.',
    funFact: 'Lithium is so light it can float on water — and then it reacts with it!'
  },
  {
    number: 4, symbol: 'Be', name: 'Beryllium',
    mass: 9.0122, category: 'alkaline-earth-metal',
    row: 2, col: 2,
    electronConfig: '[He] 2s²',
    electronegativity: 1.57,
    density: 1.85,
    meltingPoint: 1287,
    boilingPoint: 2469,
    yearDiscovered: 1798,
    discoveredBy: 'Louis Nicolas Vauquelin',
    phase: 'Solid',
    shells: [2, 2],
    summary: 'Beryllium is a relatively rare element in the universe and is a steel-gray, strong, lightweight, and brittle alkaline earth metal.',
    funFact: 'Emeralds get their green color from trace amounts of chromium in beryllium aluminum silicate (beryl).'
  },
  {
    number: 5, symbol: 'B', name: 'Boron',
    mass: 10.81, category: 'metalloid',
    row: 2, col: 13,
    electronConfig: '[He] 2s² 2p¹',
    electronegativity: 2.04,
    density: 2.34,
    meltingPoint: 2076,
    boilingPoint: 3927,
    yearDiscovered: 1808,
    discoveredBy: 'Joseph Louis Gay-Lussac',
    phase: 'Solid',
    shells: [2, 3],
    summary: 'Boron is a metalloid found in small amounts in meteoroids but is not found naturally on Earth. Industrial boron is produced as brown amorphous powder or as a black crystalline solid.',
    funFact: 'Boron is essential for plant growth, but toxic to plants in excess amounts.'
  },
  {
    number: 6, symbol: 'C', name: 'Carbon',
    mass: 12.011, category: 'nonmetal',
    row: 2, col: 14,
    electronConfig: '[He] 2s² 2p²',
    electronegativity: 2.55,
    density: 2.267,
    meltingPoint: 3550,
    boilingPoint: 4027,
    yearDiscovered: -3750,
    discoveredBy: 'Ancient',
    phase: 'Solid',
    shells: [2, 4],
    summary: 'Carbon is the basis for all known life. It can form more compounds than any other element, with almost 10 million pure organic compounds described to date.',
    funFact: 'Diamond and graphite are both pure carbon — but diamond is the hardest natural substance while graphite is one of the softest.'
  },
  {
    number: 7, symbol: 'N', name: 'Nitrogen',
    mass: 14.007, category: 'nonmetal',
    row: 2, col: 15,
    electronConfig: '[He] 2s² 2p³',
    electronegativity: 3.04,
    density: 0.0012506,
    meltingPoint: -210.00,
    boilingPoint: -195.79,
    yearDiscovered: 1772,
    discoveredBy: 'Daniel Rutherford',
    phase: 'Gas',
    shells: [2, 5],
    summary: 'Nitrogen is a colorless, odorless, tasteless gas that makes up 78.09% of Earth\'s atmosphere by volume. It is essential to all living organisms as a component of amino acids and DNA.',
    funFact: 'Lightning converts atmospheric nitrogen into nitrogen compounds that fertilize the soil.'
  },
  {
    number: 8, symbol: 'O', name: 'Oxygen',
    mass: 15.999, category: 'nonmetal',
    row: 2, col: 16,
    electronConfig: '[He] 2s² 2p⁴',
    electronegativity: 3.44,
    density: 0.001429,
    meltingPoint: -218.79,
    boilingPoint: -182.96,
    yearDiscovered: 1774,
    discoveredBy: 'Joseph Priestley',
    phase: 'Gas',
    shells: [2, 6],
    summary: 'Oxygen is the third-most abundant element in the universe and the most abundant element by mass in the Earth\'s crust. It is essential for respiration in most living organisms.',
    funFact: 'Liquid oxygen is pale blue and is slightly magnetic.'
  },
  {
    number: 9, symbol: 'F', name: 'Fluorine',
    mass: 18.998, category: 'halogen',
    row: 2, col: 17,
    electronConfig: '[He] 2s² 2p⁵',
    electronegativity: 3.98,
    density: 0.001696,
    meltingPoint: -219.67,
    boilingPoint: -188.11,
    yearDiscovered: 1886,
    discoveredBy: 'Henri Moissan',
    phase: 'Gas',
    shells: [2, 7],
    summary: 'Fluorine is the most electronegative and most reactive of all elements. It is a pale yellow, highly toxic gas that can etch glass.',
    funFact: 'Fluorine is so reactive that it can even cause water to burn.'
  },
  {
    number: 10, symbol: 'Ne', name: 'Neon',
    mass: 20.180, category: 'noble-gas',
    row: 2, col: 18,
    electronConfig: '[He] 2s² 2p⁶',
    electronegativity: null,
    density: 0.0008999,
    meltingPoint: -248.59,
    boilingPoint: -246.08,
    yearDiscovered: 1898,
    discoveredBy: 'William Ramsay',
    phase: 'Gas',
    shells: [2, 8],
    summary: 'Neon is a noble gas that gives a distinct reddish-orange glow when used in discharge tubes and neon lamps. It is the fifth most abundant element in the universe.',
    funFact: 'Despite the name "neon signs," most colored signs actually use other gases — true neon glows only red-orange.'
  },
  // ═══════════════════════ Period 3 ═══════════════════════
  {
    number: 11, symbol: 'Na', name: 'Sodium',
    mass: 22.990, category: 'alkali-metal',
    row: 3, col: 1,
    electronConfig: '[Ne] 3s¹',
    electronegativity: 0.93,
    density: 0.971,
    meltingPoint: 97.794,
    boilingPoint: 882.94,
    yearDiscovered: 1807,
    discoveredBy: 'Humphry Davy',
    phase: 'Solid',
    shells: [2, 8, 1],
    summary: 'Sodium is a soft, silvery-white, highly reactive alkali metal. In the form of table salt (NaCl), it is essential for animal nutrition.',
    funFact: 'Sodium vapor lamps produce the familiar yellow glow of many street lights.'
  },
  {
    number: 12, symbol: 'Mg', name: 'Magnesium',
    mass: 24.305, category: 'alkaline-earth-metal',
    row: 3, col: 2,
    electronConfig: '[Ne] 3s²',
    electronegativity: 1.31,
    density: 1.738,
    meltingPoint: 650,
    boilingPoint: 1091,
    yearDiscovered: 1755,
    discoveredBy: 'Joseph Black',
    phase: 'Solid',
    shells: [2, 8, 2],
    summary: 'Magnesium is a shiny gray solid that is lightweight and strong. It is the eighth most abundant element in the Earth\'s crust and is essential to all known living organisms.',
    funFact: 'Magnesium burns with an intensely bright white light, which is why it was once used in camera flash powder.'
  },
  {
    number: 13, symbol: 'Al', name: 'Aluminum',
    mass: 26.982, category: 'post-transition-metal',
    row: 3, col: 13,
    electronConfig: '[Ne] 3s² 3p¹',
    electronegativity: 1.61,
    density: 2.698,
    meltingPoint: 660.32,
    boilingPoint: 2519,
    yearDiscovered: 1825,
    discoveredBy: 'Hans Christian Ørsted',
    phase: 'Solid',
    shells: [2, 8, 3],
    summary: 'Aluminum is the most abundant metal in the Earth\'s crust. It is silvery-white, soft, non-magnetic, and ductile, widely used in the aerospace and packaging industries.',
    funFact: 'Before an efficient production method was found, aluminum was more valuable than gold — Napoleon III served his most honored guests with aluminum utensils.'
  },
  {
    number: 14, symbol: 'Si', name: 'Silicon',
    mass: 28.086, category: 'metalloid',
    row: 3, col: 14,
    electronConfig: '[Ne] 3s² 3p²',
    electronegativity: 1.90,
    density: 2.3296,
    meltingPoint: 1414,
    boilingPoint: 3265,
    yearDiscovered: 1824,
    discoveredBy: 'Jöns Jacob Berzelius',
    phase: 'Solid',
    shells: [2, 8, 4],
    summary: 'Silicon is the second most abundant element in Earth\'s crust after oxygen. It is the basis of the semiconductor industry and modern electronics.',
    funFact: 'Silicon Valley is named after this element because of its use in computer chips.'
  },
  {
    number: 15, symbol: 'P', name: 'Phosphorus',
    mass: 30.974, category: 'nonmetal',
    row: 3, col: 15,
    electronConfig: '[Ne] 3s² 3p³',
    electronegativity: 2.19,
    density: 1.82,
    meltingPoint: 44.15,
    boilingPoint: 280.5,
    yearDiscovered: 1669,
    discoveredBy: 'Hennig Brand',
    phase: 'Solid',
    shells: [2, 8, 5],
    summary: 'Phosphorus is essential for life. It is a component of DNA, RNA, ATP, and the phospholipids that form cell membranes. It exists in several allotropic forms including white, red, and black phosphorus.',
    funFact: 'Phosphorus was discovered by an alchemist who was searching for the philosopher\'s stone — in urine.'
  },
  {
    number: 16, symbol: 'S', name: 'Sulfur',
    mass: 32.06, category: 'nonmetal',
    row: 3, col: 16,
    electronConfig: '[Ne] 3s² 3p⁴',
    electronegativity: 2.58,
    density: 2.067,
    meltingPoint: 115.21,
    boilingPoint: 444.6,
    yearDiscovered: -500,
    discoveredBy: 'Ancient',
    phase: 'Solid',
    shells: [2, 8, 6],
    summary: 'Sulfur is a bright yellow crystalline solid at room temperature. Known since antiquity, it is used in matches, gunpowder, medicines, rubber vulcanization, and fertilizers.',
    funFact: 'Io, one of Jupiter\'s moons, has over 400 active volcanoes that erupt sulfur, giving it a yellow-orange appearance.'
  },
  {
    number: 17, symbol: 'Cl', name: 'Chlorine',
    mass: 35.45, category: 'halogen',
    row: 3, col: 17,
    electronConfig: '[Ne] 3s² 3p⁵',
    electronegativity: 3.16,
    density: 0.003214,
    meltingPoint: -101.5,
    boilingPoint: -34.04,
    yearDiscovered: 1774,
    discoveredBy: 'Carl Wilhelm Scheele',
    phase: 'Gas',
    shells: [2, 8, 7],
    summary: 'Chlorine is a yellow-green gas with a pungent, suffocating odor. It is widely used for water purification, disinfection, and in the production of many consumer products.',
    funFact: 'The smell of "chlorine" in swimming pools is actually chloramines — compounds formed when chlorine reacts with sweat and urine.'
  },
  {
    number: 18, symbol: 'Ar', name: 'Argon',
    mass: 39.948, category: 'noble-gas',
    row: 3, col: 18,
    electronConfig: '[Ne] 3s² 3p⁶',
    electronegativity: null,
    density: 0.0017837,
    meltingPoint: -189.34,
    boilingPoint: -185.85,
    yearDiscovered: 1894,
    discoveredBy: 'Lord Rayleigh',
    phase: 'Gas',
    shells: [2, 8, 8],
    summary: 'Argon is the third most abundant gas in Earth\'s atmosphere. It is used in welding, light bulbs, and as a protective atmosphere for growing silicon and germanium crystals.',
    funFact: 'Argon\'s name comes from the Greek "argos" meaning "lazy" or "idle" because of its extreme lack of reactivity.'
  },
  // ═══════════════════════ Period 4 ═══════════════════════
  {
    number: 19, symbol: 'K', name: 'Potassium',
    mass: 39.098, category: 'alkali-metal',
    row: 4, col: 1,
    electronConfig: '[Ar] 4s¹',
    electronegativity: 0.82,
    density: 0.862,
    meltingPoint: 63.5,
    boilingPoint: 759,
    yearDiscovered: 1807,
    discoveredBy: 'Humphry Davy',
    phase: 'Solid',
    shells: [2, 8, 8, 1],
    summary: 'Potassium is a silvery-white metal soft enough to cut with a knife. It is vital for cell function in all living organisms and is abundant in many foods.',
    funFact: 'Bananas are famously associated with potassium, but avocados and potatoes actually contain more.'
  },
  {
    number: 20, symbol: 'Ca', name: 'Calcium',
    mass: 40.078, category: 'alkaline-earth-metal',
    row: 4, col: 2,
    electronConfig: '[Ar] 4s²',
    electronegativity: 1.00,
    density: 1.55,
    meltingPoint: 842,
    boilingPoint: 1484,
    yearDiscovered: 1808,
    discoveredBy: 'Humphry Davy',
    phase: 'Solid',
    shells: [2, 8, 8, 2],
    summary: 'Calcium is the most abundant metal in the human body. It is essential for bones, teeth, nerve signaling, and muscle contraction.',
    funFact: 'The human body contains about 1 kg of calcium, 99% of which is in bones and teeth.'
  },
  {
    number: 21, symbol: 'Sc', name: 'Scandium',
    mass: 44.956, category: 'transition-metal',
    row: 4, col: 3,
    electronConfig: '[Ar] 3d¹ 4s²',
    electronegativity: 1.36,
    density: 2.989,
    meltingPoint: 1541,
    boilingPoint: 2836,
    yearDiscovered: 1879,
    discoveredBy: 'Lars Fredrik Nilson',
    phase: 'Solid',
    shells: [2, 8, 9, 2],
    summary: 'Scandium is a soft, silvery transition metal that develops a slightly yellowish or pinkish tint when oxidized. It is used in aerospace components and sports equipment.',
    funFact: 'Scandium-aluminum alloys are used in some high-end baseball bats and bicycle frames.'
  },
  {
    number: 22, symbol: 'Ti', name: 'Titanium',
    mass: 47.867, category: 'transition-metal',
    row: 4, col: 4,
    electronConfig: '[Ar] 3d² 4s²',
    electronegativity: 1.54,
    density: 4.54,
    meltingPoint: 1668,
    boilingPoint: 3287,
    yearDiscovered: 1791,
    discoveredBy: 'William Gregor',
    phase: 'Solid',
    shells: [2, 8, 10, 2],
    summary: 'Titanium is a lustrous transition metal known for its high strength-to-density ratio and excellent corrosion resistance. It is widely used in aerospace, medical implants, and jewelry.',
    funFact: 'Titanium is as strong as steel but 45% lighter.'
  },
  {
    number: 23, symbol: 'V', name: 'Vanadium',
    mass: 50.942, category: 'transition-metal',
    row: 4, col: 5,
    electronConfig: '[Ar] 3d³ 4s²',
    electronegativity: 1.63,
    density: 6.11,
    meltingPoint: 1910,
    boilingPoint: 3407,
    yearDiscovered: 1801,
    discoveredBy: 'Andrés Manuel del Río',
    phase: 'Solid',
    shells: [2, 8, 11, 2],
    summary: 'Vanadium is a hard, silvery-grey, malleable transition metal. It is used mainly to produce specialty steel alloys such as high-speed tool steels.',
    funFact: 'Vanadium compounds produce some of the most vivid colors in ceramics and glass.'
  },
  {
    number: 24, symbol: 'Cr', name: 'Chromium',
    mass: 51.996, category: 'transition-metal',
    row: 4, col: 6,
    electronConfig: '[Ar] 3d⁵ 4s¹',
    electronegativity: 1.66,
    density: 7.15,
    meltingPoint: 1907,
    boilingPoint: 2671,
    yearDiscovered: 1797,
    discoveredBy: 'Louis Nicolas Vauquelin',
    phase: 'Solid',
    shells: [2, 8, 13, 1],
    summary: 'Chromium is a steely-grey, lustrous, hard transition metal that takes a high polish. It is valued for its high corrosion resistance and hardness.',
    funFact: 'Rubies are red because of trace amounts of chromium in aluminum oxide crystals.'
  },
  {
    number: 25, symbol: 'Mn', name: 'Manganese',
    mass: 54.938, category: 'transition-metal',
    row: 4, col: 7,
    electronConfig: '[Ar] 3d⁵ 4s²',
    electronegativity: 1.55,
    density: 7.44,
    meltingPoint: 1246,
    boilingPoint: 2061,
    yearDiscovered: 1774,
    discoveredBy: 'Johan Gottlieb Gahn',
    phase: 'Solid',
    shells: [2, 8, 13, 2],
    summary: 'Manganese is a hard, brittle, silvery metal often used in steel production to improve strength, hardness, and wear resistance.',
    funFact: 'Manganese dioxide has been used as a pigment since the Stone Age — cave paintings 30,000 years old contain it.'
  },
  {
    number: 26, symbol: 'Fe', name: 'Iron',
    mass: 55.845, category: 'transition-metal',
    row: 4, col: 8,
    electronConfig: '[Ar] 3d⁶ 4s²',
    electronegativity: 1.83,
    density: 7.874,
    meltingPoint: 1538,
    boilingPoint: 2862,
    yearDiscovered: -5000,
    discoveredBy: 'Ancient',
    phase: 'Solid',
    shells: [2, 8, 14, 2],
    summary: 'Iron is the most common element on Earth by mass and the fourth most common in the Earth\'s crust. It is the primary component of steel and is essential for hemoglobin in blood.',
    funFact: 'Earth\'s core is primarily iron, generating the magnetic field that protects us from solar radiation.'
  },
  {
    number: 27, symbol: 'Co', name: 'Cobalt',
    mass: 58.933, category: 'transition-metal',
    row: 4, col: 9,
    electronConfig: '[Ar] 3d⁷ 4s²',
    electronegativity: 1.88,
    density: 8.90,
    meltingPoint: 1495,
    boilingPoint: 2927,
    yearDiscovered: 1735,
    discoveredBy: 'Georg Brandt',
    phase: 'Solid',
    shells: [2, 8, 15, 2],
    summary: 'Cobalt is a hard, lustrous, bluish-gray metal used in lithium-ion batteries, blue pigments, and high-temperature alloys.',
    funFact: 'Cobalt blue has been used as a pigment since ancient times — it colors the famous blue glass of the Egyptian pharaohs.'
  },
  {
    number: 28, symbol: 'Ni', name: 'Nickel',
    mass: 58.693, category: 'transition-metal',
    row: 4, col: 10,
    electronConfig: '[Ar] 3d⁸ 4s²',
    electronegativity: 1.91,
    density: 8.912,
    meltingPoint: 1455,
    boilingPoint: 2913,
    yearDiscovered: 1751,
    discoveredBy: 'Axel Fredrik Cronstedt',
    phase: 'Solid',
    shells: [2, 8, 16, 2],
    summary: 'Nickel is a silvery-white lustrous metal with a slight golden tinge, valued for its resistance to corrosion. It is used in stainless steel, batteries, and coins.',
    funFact: 'The US "nickel" coin is actually 75% copper and only 25% nickel.'
  },
  {
    number: 29, symbol: 'Cu', name: 'Copper',
    mass: 63.546, category: 'transition-metal',
    row: 4, col: 11,
    electronConfig: '[Ar] 3d¹⁰ 4s¹',
    electronegativity: 1.90,
    density: 8.96,
    meltingPoint: 1084.62,
    boilingPoint: 2560,
    yearDiscovered: -9000,
    discoveredBy: 'Ancient',
    phase: 'Solid',
    shells: [2, 8, 18, 1],
    summary: 'Copper was one of the first metals used by humans. Its excellent thermal and electrical conductivity make it essential for wiring and electronics.',
    funFact: 'The Statue of Liberty is covered in 80 tons of copper — which is why it turned green over time.'
  },
  {
    number: 30, symbol: 'Zn', name: 'Zinc',
    mass: 65.38, category: 'transition-metal',
    row: 4, col: 12,
    electronConfig: '[Ar] 3d¹⁰ 4s²',
    electronegativity: 1.65,
    density: 7.134,
    meltingPoint: 419.53,
    boilingPoint: 907,
    yearDiscovered: 1746,
    discoveredBy: 'Andreas Marggraf',
    phase: 'Solid',
    shells: [2, 8, 18, 2],
    summary: 'Zinc is a bluish-white, lustrous metal. It is the 24th most abundant element in Earth\'s crust and is widely used to galvanize steel to prevent corrosion.',
    funFact: 'US pennies minted after 1982 are actually 97.5% zinc with a thin copper coating.'
  },
  {
    number: 31, symbol: 'Ga', name: 'Gallium',
    mass: 69.723, category: 'post-transition-metal',
    row: 4, col: 13,
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹',
    electronegativity: 1.81,
    density: 5.907,
    meltingPoint: 29.76,
    boilingPoint: 2204,
    yearDiscovered: 1875,
    discoveredBy: 'Lecoq de Boisbaudran',
    phase: 'Solid',
    shells: [2, 8, 18, 3],
    summary: 'Gallium is a soft, silvery metal that melts just above room temperature. It is used in semiconductors, LEDs, and solar panels.',
    funFact: 'Gallium melts at 29.76°C — you can melt it by holding it in the palm of your hand!'
  },
  {
    number: 32, symbol: 'Ge', name: 'Germanium',
    mass: 72.630, category: 'metalloid',
    row: 4, col: 14,
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p²',
    electronegativity: 2.01,
    density: 5.323,
    meltingPoint: 938.25,
    boilingPoint: 2833,
    yearDiscovered: 1886,
    discoveredBy: 'Clemens Winkler',
    phase: 'Solid',
    shells: [2, 8, 18, 4],
    summary: 'Germanium is a lustrous, hard-brittle, grayish-white metalloid. It was one of the first semiconductor materials used in transistors.',
    funFact: 'Germanium was predicted by Mendeleev as "eka-silicon" in 1869, 17 years before it was actually discovered.'
  },
  {
    number: 33, symbol: 'As', name: 'Arsenic',
    mass: 74.922, category: 'metalloid',
    row: 4, col: 15,
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p³',
    electronegativity: 2.18,
    density: 5.776,
    meltingPoint: 817,
    boilingPoint: 614,
    yearDiscovered: 815,
    discoveredBy: 'Jabir ibn Hayyan',
    phase: 'Solid',
    shells: [2, 8, 18, 5],
    summary: 'Arsenic is a metalloid known since antiquity. While famously toxic, tiny amounts are essential for some organisms, and gallium arsenide is an important semiconductor.',
    funFact: 'Arsenic was called "inheritance powder" in the Middle Ages because it was frequently used to speed up inheritances.'
  },
  {
    number: 34, symbol: 'Se', name: 'Selenium',
    mass: 78.971, category: 'nonmetal',
    row: 4, col: 16,
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴',
    electronegativity: 2.55,
    density: 4.809,
    meltingPoint: 221,
    boilingPoint: 685,
    yearDiscovered: 1817,
    discoveredBy: 'Jöns Jacob Berzelius',
    phase: 'Solid',
    shells: [2, 8, 18, 6],
    summary: 'Selenium is a nonmetal with properties intermediate between sulfur and tellurium. It is an essential trace element for humans and is used in glassmaking and electronics.',
    funFact: 'Selenium\'s electrical resistance decreases when light shines on it, which is how early photocopiers worked.'
  },
  {
    number: 35, symbol: 'Br', name: 'Bromine',
    mass: 79.904, category: 'halogen',
    row: 4, col: 17,
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵',
    electronegativity: 2.96,
    density: 3.122,
    meltingPoint: -7.2,
    boilingPoint: 58.8,
    yearDiscovered: 1826,
    discoveredBy: 'Antoine Jérôme Balard',
    phase: 'Liquid',
    shells: [2, 8, 18, 7],
    summary: 'Bromine is the only nonmetallic element that is liquid at room temperature. It is a dense, reddish-brown liquid with a pungent odor.',
    funFact: 'Tyrian purple, the exclusive dye of Roman emperors, comes from a bromine compound in sea snails.'
  },
  {
    number: 36, symbol: 'Kr', name: 'Krypton',
    mass: 83.798, category: 'noble-gas',
    row: 4, col: 18,
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶',
    electronegativity: 3.00,
    density: 0.003733,
    meltingPoint: -157.36,
    boilingPoint: -153.22,
    yearDiscovered: 1898,
    discoveredBy: 'William Ramsay',
    phase: 'Gas',
    shells: [2, 8, 18, 8],
    summary: 'Krypton is a colorless, odorless noble gas that produces a brilliant white light when electrified. It is used in certain fluorescent lamps and photographic flash equipment.',
    funFact: 'Superman\'s home planet is named after this element, but real krypton won\'t harm anyone (it\'s inert).'
  },
  // ═══════════════════════ Period 5 ═══════════════════════
  {
    number: 37, symbol: 'Rb', name: 'Rubidium',
    mass: 85.468, category: 'alkali-metal',
    row: 5, col: 1,
    electronConfig: '[Kr] 5s¹',
    electronegativity: 0.82,
    density: 1.532,
    meltingPoint: 39.31,
    boilingPoint: 688,
    yearDiscovered: 1861,
    discoveredBy: 'Robert Bunsen',
    phase: 'Solid',
    shells: [2, 8, 18, 8, 1],
    summary: 'Rubidium is a soft, silvery-white alkali metal that ignites spontaneously in air and reacts violently with water. It is used in atomic clocks and specialized electronics.',
    funFact: 'Rubidium atomic clocks are so accurate they would lose less than one second in 300 million years.'
  },
  {
    number: 38, symbol: 'Sr', name: 'Strontium',
    mass: 87.62, category: 'alkaline-earth-metal',
    row: 5, col: 2,
    electronConfig: '[Kr] 5s²',
    electronegativity: 0.95,
    density: 2.64,
    meltingPoint: 777,
    boilingPoint: 1377,
    yearDiscovered: 1790,
    discoveredBy: 'Adair Crawford',
    phase: 'Solid',
    shells: [2, 8, 18, 8, 2],
    summary: 'Strontium is a soft, silver-yellow alkaline earth metal. It is best known for producing the brilliant red color in fireworks and signal flares.',
    funFact: 'The brilliant red color of fireworks comes from strontium compounds.'
  },
  {
    number: 39, symbol: 'Y', name: 'Yttrium',
    mass: 88.906, category: 'transition-metal',
    row: 5, col: 3,
    electronConfig: '[Kr] 4d¹ 5s²',
    electronegativity: 1.22,
    density: 4.469,
    meltingPoint: 1526,
    boilingPoint: 3345,
    yearDiscovered: 1794,
    discoveredBy: 'Johan Gadolin',
    phase: 'Solid',
    shells: [2, 8, 18, 9, 2],
    summary: 'Yttrium is a silvery-metallic transition metal used in LEDs, lasers, and superconductors. It is one of several elements named after the village of Ytterby in Sweden.',
    funFact: 'Four elements were named after the tiny Swedish village of Ytterby: yttrium, ytterbium, erbium, and terbium.'
  },
  {
    number: 40, symbol: 'Zr', name: 'Zirconium',
    mass: 91.224, category: 'transition-metal',
    row: 5, col: 4,
    electronConfig: '[Kr] 4d² 5s²',
    electronegativity: 1.33,
    density: 6.506,
    meltingPoint: 1855,
    boilingPoint: 4409,
    yearDiscovered: 1789,
    discoveredBy: 'Martin Heinrich Klaproth',
    phase: 'Solid',
    shells: [2, 8, 18, 10, 2],
    summary: 'Zirconium is a lustrous, grey-white metal that is strong, malleable, and highly resistant to corrosion. It is widely used in nuclear reactors due to its low neutron absorption.',
    funFact: 'Cubic zirconia (ZrO₂) is the most popular diamond simulant because of its brilliance and low cost.'
  },
  {
    number: 41, symbol: 'Nb', name: 'Niobium',
    mass: 92.906, category: 'transition-metal',
    row: 5, col: 5,
    electronConfig: '[Kr] 4d⁴ 5s¹',
    electronegativity: 1.6,
    density: 8.57,
    meltingPoint: 2477,
    boilingPoint: 4744,
    yearDiscovered: 1801,
    discoveredBy: 'Charles Hatchett',
    phase: 'Solid',
    shells: [2, 8, 18, 12, 1],
    summary: 'Niobium is a soft, grey, ductile transition metal used in superconducting magnets, aircraft engines, and hypoallergenic jewelry.',
    funFact: 'The superconducting magnets in the Large Hadron Collider at CERN use niobium-titanium wire.'
  },
  {
    number: 42, symbol: 'Mo', name: 'Molybdenum',
    mass: 95.95, category: 'transition-metal',
    row: 5, col: 6,
    electronConfig: '[Kr] 4d⁵ 5s¹',
    electronegativity: 2.16,
    density: 10.22,
    meltingPoint: 2623,
    boilingPoint: 4639,
    yearDiscovered: 1781,
    discoveredBy: 'Carl Wilhelm Scheele',
    phase: 'Solid',
    shells: [2, 8, 18, 13, 1],
    summary: 'Molybdenum is a silvery metal with the sixth-highest melting point of any element. It is used as an alloying agent in steel to increase strength and high-temperature resistance.',
    funFact: 'Molybdenum is an essential trace element for all living organisms — it helps enzymes process nitrogen.'
  },
  {
    number: 43, symbol: 'Tc', name: 'Technetium',
    mass: '(98)', category: 'transition-metal',
    row: 5, col: 7,
    electronConfig: '[Kr] 4d⁵ 5s²',
    electronegativity: 1.9,
    density: 11.5,
    meltingPoint: 2157,
    boilingPoint: 4265,
    yearDiscovered: 1937,
    discoveredBy: 'Carlo Perrier',
    phase: 'Solid',
    shells: [2, 8, 18, 13, 2],
    summary: 'Technetium was the first artificially produced element. It is radioactive with no stable isotopes and is used extensively in medical diagnostic imaging.',
    funFact: 'Technetium-99m is used in over 20 million medical diagnostic procedures worldwide each year.'
  },
  {
    number: 44, symbol: 'Ru', name: 'Ruthenium',
    mass: 101.07, category: 'transition-metal',
    row: 5, col: 8,
    electronConfig: '[Kr] 4d⁷ 5s¹',
    electronegativity: 2.2,
    density: 12.37,
    meltingPoint: 2334,
    boilingPoint: 4150,
    yearDiscovered: 1844,
    discoveredBy: 'Karl Ernst Claus',
    phase: 'Solid',
    shells: [2, 8, 18, 15, 1],
    summary: 'Ruthenium is a rare transition metal belonging to the platinum group. It is used to harden platinum and palladium alloys and in electronics.',
    funFact: 'Ruthenium is named after Ruthenia, the Latin name for Russia.'
  },
  {
    number: 45, symbol: 'Rh', name: 'Rhodium',
    mass: 102.91, category: 'transition-metal',
    row: 5, col: 9,
    electronConfig: '[Kr] 4d⁸ 5s¹',
    electronegativity: 2.28,
    density: 12.41,
    meltingPoint: 1964,
    boilingPoint: 3695,
    yearDiscovered: 1803,
    discoveredBy: 'William Hyde Wollaston',
    phase: 'Solid',
    shells: [2, 8, 18, 16, 1],
    summary: 'Rhodium is an ultra-rare, silvery-white, hard, corrosion-resistant member of the platinum group. It is primarily used in catalytic converters for automobiles.',
    funFact: 'Rhodium is one of the most expensive precious metals, sometimes exceeding gold by 10x or more.'
  },
  {
    number: 46, symbol: 'Pd', name: 'Palladium',
    mass: 106.42, category: 'transition-metal',
    row: 5, col: 10,
    electronConfig: '[Kr] 4d¹⁰',
    electronegativity: 2.20,
    density: 12.02,
    meltingPoint: 1554.9,
    boilingPoint: 2963,
    yearDiscovered: 1803,
    discoveredBy: 'William Hyde Wollaston',
    phase: 'Solid',
    shells: [2, 8, 18, 18],
    summary: 'Palladium is a rare, lustrous silvery-white metal that is extremely ductile. It is crucial for catalytic converters, electronics, and jewelry.',
    funFact: 'Palladium can absorb up to 900 times its own volume of hydrogen at room temperature.'
  },
  {
    number: 47, symbol: 'Ag', name: 'Silver',
    mass: 107.87, category: 'transition-metal',
    row: 5, col: 11,
    electronConfig: '[Kr] 4d¹⁰ 5s¹',
    electronegativity: 1.93,
    density: 10.501,
    meltingPoint: 961.78,
    boilingPoint: 2162,
    yearDiscovered: -5000,
    discoveredBy: 'Ancient',
    phase: 'Solid',
    shells: [2, 8, 18, 18, 1],
    summary: 'Silver has the highest electrical conductivity, thermal conductivity, and reflectivity of any metal. It has been valued as a precious metal for thousands of years.',
    funFact: 'Silver is the best electrical conductor of all the elements, which is why it\'s used in high-end electronics.'
  },
  {
    number: 48, symbol: 'Cd', name: 'Cadmium',
    mass: 112.41, category: 'transition-metal',
    row: 5, col: 12,
    electronConfig: '[Kr] 4d¹⁰ 5s²',
    electronegativity: 1.69,
    density: 8.69,
    meltingPoint: 321.07,
    boilingPoint: 767,
    yearDiscovered: 1817,
    discoveredBy: 'Karl Samuel Leberecht Hermann',
    phase: 'Solid',
    shells: [2, 8, 18, 18, 2],
    summary: 'Cadmium is a soft, bluish-white metal that is chemically similar to zinc. While toxic, it is used in batteries, pigments, and coatings.',
    funFact: 'Cadmium yellow and cadmium red are vivid, light-fast pigments favored by artists like Van Gogh and Monet.'
  },
  {
    number: 49, symbol: 'In', name: 'Indium',
    mass: 114.82, category: 'post-transition-metal',
    row: 5, col: 13,
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹',
    electronegativity: 1.78,
    density: 7.31,
    meltingPoint: 156.6,
    boilingPoint: 2072,
    yearDiscovered: 1863,
    discoveredBy: 'Ferdinand Reich',
    phase: 'Solid',
    shells: [2, 8, 18, 18, 3],
    summary: 'Indium is a soft, malleable post-transition metal. Its most important application is in indium tin oxide (ITO), used for transparent conductive coatings in touchscreens.',
    funFact: 'Every touchscreen device you use likely contains indium tin oxide as its transparent conducting layer.'
  },
  {
    number: 50, symbol: 'Sn', name: 'Tin',
    mass: 118.71, category: 'post-transition-metal',
    row: 5, col: 14,
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p²',
    electronegativity: 1.96,
    density: 7.287,
    meltingPoint: 231.93,
    boilingPoint: 2602,
    yearDiscovered: -3500,
    discoveredBy: 'Ancient',
    phase: 'Solid',
    shells: [2, 8, 18, 18, 4],
    summary: 'Tin is a silvery metal that has been used since the Bronze Age. It is soft, malleable, and resists corrosion, making it ideal for coating other metals.',
    funFact: '"Tin cry" is the characteristic crackling sound tin makes when bent, caused by crystal twinning.'
  },
  {
    number: 51, symbol: 'Sb', name: 'Antimony',
    mass: 121.76, category: 'metalloid',
    row: 5, col: 15,
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p³',
    electronegativity: 2.05,
    density: 6.685,
    meltingPoint: 630.63,
    boilingPoint: 1587,
    yearDiscovered: -3000,
    discoveredBy: 'Ancient',
    phase: 'Solid',
    shells: [2, 8, 18, 18, 5],
    summary: 'Antimony is a lustrous gray metalloid found in nature mainly as stibnite. It is used in flame retardants, lead-acid batteries, and as an alloying agent.',
    funFact: 'Ancient Egyptians used antimony sulfide (stibnite) as eyeliner — the original "kohl" cosmetic.'
  },
  {
    number: 52, symbol: 'Te', name: 'Tellurium',
    mass: 127.60, category: 'metalloid',
    row: 5, col: 16,
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴',
    electronegativity: 2.1,
    density: 6.232,
    meltingPoint: 449.51,
    boilingPoint: 988,
    yearDiscovered: 1783,
    discoveredBy: 'Franz-Joseph Müller von Reichenstein',
    phase: 'Solid',
    shells: [2, 8, 18, 18, 6],
    summary: 'Tellurium is a brittle, mildly toxic, rare metalloid. It is used in solar cells, thermoelectric devices, and as an alloying agent in steel and copper.',
    funFact: 'Exposure to even tiny amounts of tellurium gives a person an intense garlic-like breath odor for weeks.'
  },
  {
    number: 53, symbol: 'I', name: 'Iodine',
    mass: 126.90, category: 'halogen',
    row: 5, col: 17,
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵',
    electronegativity: 2.66,
    density: 4.93,
    meltingPoint: 113.7,
    boilingPoint: 184.3,
    yearDiscovered: 1811,
    discoveredBy: 'Bernard Courtois',
    phase: 'Solid',
    shells: [2, 8, 18, 18, 7],
    summary: 'Iodine is a dark purple-black nonmetallic solid that sublimes into a violet gas. It is an essential element for thyroid hormone production in humans.',
    funFact: 'Iodized table salt was introduced in 1924 to prevent goiter, one of the most successful public health initiatives ever.'
  },
  {
    number: 54, symbol: 'Xe', name: 'Xenon',
    mass: 131.29, category: 'noble-gas',
    row: 5, col: 18,
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶',
    electronegativity: 2.60,
    density: 0.005887,
    meltingPoint: -111.75,
    boilingPoint: -108.09,
    yearDiscovered: 1898,
    discoveredBy: 'William Ramsay',
    phase: 'Gas',
    shells: [2, 8, 18, 18, 8],
    summary: 'Xenon is a colorless, dense, odorless noble gas. Despite being "noble," it can form compounds under special conditions. It is used in flash lamps, arc lamps, and anesthesia.',
    funFact: 'Xenon was the first noble gas found to form true chemical compounds, overturning decades of chemistry dogma.'
  },
  // ═══════════════════════ Period 6 ═══════════════════════
  {
    number: 55, symbol: 'Cs', name: 'Cesium',
    mass: 132.91, category: 'alkali-metal',
    row: 6, col: 1,
    electronConfig: '[Xe] 6s¹',
    electronegativity: 0.79,
    density: 1.873,
    meltingPoint: 28.44,
    boilingPoint: 671,
    yearDiscovered: 1860,
    discoveredBy: 'Robert Bunsen',
    phase: 'Solid',
    shells: [2, 8, 18, 18, 8, 1],
    summary: 'Cesium is a soft, silvery-golden alkali metal with a melting point of 28.44°C, making it one of only five metals that are liquid near room temperature.',
    funFact: 'The international definition of one second is based on 9,192,631,770 oscillations of a cesium-133 atom.'
  },
  {
    number: 56, symbol: 'Ba', name: 'Barium',
    mass: 137.33, category: 'alkaline-earth-metal',
    row: 6, col: 2,
    electronConfig: '[Xe] 6s²',
    electronegativity: 0.89,
    density: 3.594,
    meltingPoint: 727,
    boilingPoint: 1845,
    yearDiscovered: 1808,
    discoveredBy: 'Humphry Davy',
    phase: 'Solid',
    shells: [2, 8, 18, 18, 8, 2],
    summary: 'Barium is a soft, silvery alkaline earth metal. Its compounds are used in drilling fluids for oil wells, X-ray imaging, and green fireworks.',
    funFact: 'Barium sulfate "milkshakes" are drunk by patients before X-rays to make the digestive system visible.'
  },
  // Lanthanides (57–71) — shown in row 8
  {
    number: 57, symbol: 'La', name: 'Lanthanum',
    mass: 138.91, category: 'lanthanide',
    row: 8, col: 3,
    electronConfig: '[Xe] 5d¹ 6s²',
    electronegativity: 1.10,
    density: 6.145,
    meltingPoint: 920,
    boilingPoint: 3464,
    yearDiscovered: 1839,
    discoveredBy: 'Carl Gustaf Mosander',
    phase: 'Solid',
    shells: [2, 8, 18, 18, 9, 2],
    summary: 'Lanthanum is a soft, silvery white metal that gives the lanthanide series its name. It is used in camera and telescope lenses and hybrid car batteries.',
    funFact: 'Lanthanum\'s name means "hidden one" in Greek because it lay hidden in cerium oxide for 36 years.'
  },
  {
    number: 58, symbol: 'Ce', name: 'Cerium',
    mass: 140.12, category: 'lanthanide',
    row: 8, col: 4,
    electronConfig: '[Xe] 4f¹ 5d¹ 6s²',
    electronegativity: 1.12,
    density: 6.77,
    meltingPoint: 799,
    boilingPoint: 3443,
    yearDiscovered: 1803,
    discoveredBy: 'Jöns Jacob Berzelius',
    phase: 'Solid',
    shells: [2, 8, 18, 19, 9, 2],
    summary: 'Cerium is the most abundant of the rare earth elements. It is used in catalytic converters, self-cleaning ovens, and glass polishing.',
    funFact: 'Cerium oxide is used in the walls of self-cleaning ovens — it catalyzes the oxidation of cooking residues.'
  },
  {
    number: 59, symbol: 'Pr', name: 'Praseodymium',
    mass: 140.91, category: 'lanthanide',
    row: 8, col: 5,
    electronConfig: '[Xe] 4f³ 6s²',
    electronegativity: 1.13,
    density: 6.773,
    meltingPoint: 931,
    boilingPoint: 3520,
    yearDiscovered: 1885,
    discoveredBy: 'Carl Auer von Welsbach',
    phase: 'Solid',
    shells: [2, 8, 18, 21, 8, 2],
    summary: 'Praseodymium is a soft, silvery, malleable metal that develops a green oxide coating in air. It is used in high-strength magnets and aircraft engines.',
    funFact: 'Praseodymium gives glass a distinctive bright yellow-green color and is used in welder\'s goggles.'
  },
  {
    number: 60, symbol: 'Nd', name: 'Neodymium',
    mass: 144.24, category: 'lanthanide',
    row: 8, col: 6,
    electronConfig: '[Xe] 4f⁴ 6s²',
    electronegativity: 1.14,
    density: 7.007,
    meltingPoint: 1016,
    boilingPoint: 3074,
    yearDiscovered: 1885,
    discoveredBy: 'Carl Auer von Welsbach',
    phase: 'Solid',
    shells: [2, 8, 18, 22, 8, 2],
    summary: 'Neodymium is a bright, silvery rare earth metal used primarily to make the strongest permanent magnets available, known as neodymium magnets (NdFeB).',
    funFact: 'Neodymium magnets are so strong that two large ones snapping together can break bones.'
  },
  {
    number: 61, symbol: 'Pm', name: 'Promethium',
    mass: '(145)', category: 'lanthanide',
    row: 8, col: 7,
    electronConfig: '[Xe] 4f⁵ 6s²',
    electronegativity: 1.13,
    density: 7.26,
    meltingPoint: 1042,
    boilingPoint: 3000,
    yearDiscovered: 1945,
    discoveredBy: 'Chien Shiung Wu',
    phase: 'Solid',
    shells: [2, 8, 18, 23, 8, 2],
    summary: 'Promethium is the only lanthanide that has no stable isotopes. It is extremely rare and radioactive, used in some nuclear batteries and luminous paint.',
    funFact: 'Promethium is named after Prometheus, the Titan from Greek mythology who stole fire from the gods.'
  },
  {
    number: 62, symbol: 'Sm', name: 'Samarium',
    mass: 150.36, category: 'lanthanide',
    row: 8, col: 8,
    electronConfig: '[Xe] 4f⁶ 6s²',
    electronegativity: 1.17,
    density: 7.52,
    meltingPoint: 1072,
    boilingPoint: 1794,
    yearDiscovered: 1879,
    discoveredBy: 'Lecoq de Boisbaudran',
    phase: 'Solid',
    shells: [2, 8, 18, 24, 8, 2],
    summary: 'Samarium is a moderately hard silvery metal used in samarium-cobalt magnets, which tolerate higher temperatures than neodymium magnets.',
    funFact: 'Samarium-cobalt magnets are used in stealth technology because they maintain magnetism at extreme temperatures.'
  },
  {
    number: 63, symbol: 'Eu', name: 'Europium',
    mass: 151.96, category: 'lanthanide',
    row: 8, col: 9,
    electronConfig: '[Xe] 4f⁷ 6s²',
    electronegativity: 1.2,
    density: 5.243,
    meltingPoint: 822,
    boilingPoint: 1529,
    yearDiscovered: 1901,
    discoveredBy: 'Eugène-Anatole Demarçay',
    phase: 'Solid',
    shells: [2, 8, 18, 25, 8, 2],
    summary: 'Europium is the most reactive of the rare earth elements. It is used as a red phosphor in TV screens and as an anti-forgery measure in Euro banknotes.',
    funFact: 'Euro banknotes glow red under UV light thanks to europium compounds — an anti-counterfeiting measure.'
  },
  {
    number: 64, symbol: 'Gd', name: 'Gadolinium',
    mass: 157.25, category: 'lanthanide',
    row: 8, col: 10,
    electronConfig: '[Xe] 4f⁷ 5d¹ 6s²',
    electronegativity: 1.20,
    density: 7.895,
    meltingPoint: 1313,
    boilingPoint: 3273,
    yearDiscovered: 1880,
    discoveredBy: 'Jean Charles Galissard de Marignac',
    phase: 'Solid',
    shells: [2, 8, 18, 25, 9, 2],
    summary: 'Gadolinium is a silvery-white rare earth metal with unusual magnetic properties. It is widely used as a contrast agent in MRI scans.',
    funFact: 'Gadolinium is ferromagnetic at room temperature — one of only four elements with this property.'
  },
  {
    number: 65, symbol: 'Tb', name: 'Terbium',
    mass: 158.93, category: 'lanthanide',
    row: 8, col: 11,
    electronConfig: '[Xe] 4f⁹ 6s²',
    electronegativity: 1.2,
    density: 8.229,
    meltingPoint: 1356,
    boilingPoint: 3230,
    yearDiscovered: 1843,
    discoveredBy: 'Carl Gustaf Mosander',
    phase: 'Solid',
    shells: [2, 8, 18, 27, 8, 2],
    summary: 'Terbium is a silvery-white rare earth metal used in green phosphors for displays and fluorescent lamps, and in solid-state devices.',
    funFact: 'Terbium is what makes the green color in your smartphone and tablet screen so vivid.'
  },
  {
    number: 66, symbol: 'Dy', name: 'Dysprosium',
    mass: 162.50, category: 'lanthanide',
    row: 8, col: 12,
    electronConfig: '[Xe] 4f¹⁰ 6s²',
    electronegativity: 1.22,
    density: 8.55,
    meltingPoint: 1412,
    boilingPoint: 2567,
    yearDiscovered: 1886,
    discoveredBy: 'Lecoq de Boisbaudran',
    phase: 'Solid',
    shells: [2, 8, 18, 28, 8, 2],
    summary: 'Dysprosium is a rare earth element used in neodymium magnets to raise their resistance to demagnetization at high temperatures, critical for electric vehicles and wind turbines.',
    funFact: 'Dysprosium means "hard to get" in Greek, named for the difficulty of isolating it.'
  },
  {
    number: 67, symbol: 'Ho', name: 'Holmium',
    mass: 164.93, category: 'lanthanide',
    row: 8, col: 13,
    electronConfig: '[Xe] 4f¹¹ 6s²',
    electronegativity: 1.23,
    density: 8.795,
    meltingPoint: 1474,
    boilingPoint: 2700,
    yearDiscovered: 1878,
    discoveredBy: 'Marc Delafontaine',
    phase: 'Solid',
    shells: [2, 8, 18, 29, 8, 2],
    summary: 'Holmium is a relatively soft, silvery rare earth element with the highest magnetic moment of any naturally occurring element. It is used in medical lasers.',
    funFact: 'Holmium has the strongest magnetic field strength of any element — it\'s used to create the strongest artificial magnetic fields.'
  },
  {
    number: 68, symbol: 'Er', name: 'Erbium',
    mass: 167.26, category: 'lanthanide',
    row: 8, col: 14,
    electronConfig: '[Xe] 4f¹² 6s²',
    electronegativity: 1.24,
    density: 9.066,
    meltingPoint: 1529,
    boilingPoint: 2868,
    yearDiscovered: 1842,
    discoveredBy: 'Carl Gustaf Mosander',
    phase: 'Solid',
    shells: [2, 8, 18, 30, 8, 2],
    summary: 'Erbium is a silvery-white rare earth metal. Erbium-doped fiber amplifiers are the backbone of long-distance fiber optic communication.',
    funFact: 'Every time you use the internet, your data likely passes through erbium-doped fiber amplifiers.'
  },
  {
    number: 69, symbol: 'Tm', name: 'Thulium',
    mass: 168.93, category: 'lanthanide',
    row: 8, col: 15,
    electronConfig: '[Xe] 4f¹³ 6s²',
    electronegativity: 1.25,
    density: 9.321,
    meltingPoint: 1545,
    boilingPoint: 1950,
    yearDiscovered: 1879,
    discoveredBy: 'Per Teodor Cleve',
    phase: 'Solid',
    shells: [2, 8, 18, 31, 8, 2],
    summary: 'Thulium is the least abundant of the naturally occurring lanthanides. It is used in portable X-ray devices and high-temperature superconductors.',
    funFact: 'Thulium is the rarest naturally occurring lanthanide, yet is still more abundant in Earth\'s crust than gold.'
  },
  {
    number: 70, symbol: 'Yb', name: 'Ytterbium',
    mass: 173.05, category: 'lanthanide',
    row: 8, col: 16,
    electronConfig: '[Xe] 4f¹⁴ 6s²',
    electronegativity: 1.1,
    density: 6.965,
    meltingPoint: 819,
    boilingPoint: 1196,
    yearDiscovered: 1878,
    discoveredBy: 'Jean Charles Galissard de Marignac',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 8, 2],
    summary: 'Ytterbium is a soft, silvery rare earth element used in stainless steel alloys, stress gauges, and atomic clocks.',
    funFact: 'Ytterbium atomic clocks are among the most precise timekeeping devices ever created.'
  },
  {
    number: 71, symbol: 'Lu', name: 'Lutetium',
    mass: 174.97, category: 'lanthanide',
    row: 8, col: 17,
    electronConfig: '[Xe] 4f¹⁴ 5d¹ 6s²',
    electronegativity: 1.27,
    density: 9.84,
    meltingPoint: 1663,
    boilingPoint: 3402,
    yearDiscovered: 1907,
    discoveredBy: 'Georges Urbain',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 9, 2],
    summary: 'Lutetium is the last element in the lanthanide series. It is the hardest and densest lanthanide, used in PET scan detectors and specialized catalysts.',
    funFact: 'Lutetium is named after Lutetia, the ancient Roman name for Paris.'
  },
  // Continue Period 6 after lanthanides
  {
    number: 72, symbol: 'Hf', name: 'Hafnium',
    mass: 178.49, category: 'transition-metal',
    row: 6, col: 4,
    electronConfig: '[Xe] 4f¹⁴ 5d² 6s²',
    electronegativity: 1.3,
    density: 13.31,
    meltingPoint: 2233,
    boilingPoint: 4603,
    yearDiscovered: 1923,
    discoveredBy: 'Dirk Coster',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 10, 2],
    summary: 'Hafnium is a lustrous, silvery gray transition metal. Due to its excellent neutron absorption, it is used in nuclear reactor control rods.',
    funFact: 'Hafnium and zirconium are so chemically similar that separating them was one of the greatest challenges in chemistry.'
  },
  {
    number: 73, symbol: 'Ta', name: 'Tantalum',
    mass: 180.95, category: 'transition-metal',
    row: 6, col: 5,
    electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²',
    electronegativity: 1.5,
    density: 16.654,
    meltingPoint: 3017,
    boilingPoint: 5458,
    yearDiscovered: 1802,
    discoveredBy: 'Anders Gustaf Ekeberg',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 11, 2],
    summary: 'Tantalum is a rare, hard, blue-gray metal that is highly corrosion-resistant. It is essential for capacitors in smartphones, laptops, and other electronics.',
    funFact: 'Tantalum is named after Tantalus from Greek mythology — acids cannot dissolve it, as if the metal is "tantalized" by them.'
  },
  {
    number: 74, symbol: 'W', name: 'Tungsten',
    mass: 183.84, category: 'transition-metal',
    row: 6, col: 6,
    electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²',
    electronegativity: 2.36,
    density: 19.25,
    meltingPoint: 3422,
    boilingPoint: 5555,
    yearDiscovered: 1783,
    discoveredBy: 'Juan José Elhuyar',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 12, 2],
    summary: 'Tungsten has the highest melting point of all elements at 3,422°C. It is used in light bulb filaments, cutting tools, and military applications.',
    funFact: 'Tungsten\'s symbol "W" comes from its German name, Wolfram, meaning "wolf\'s froth" (a mineral that interfered with tin smelting).'
  },
  {
    number: 75, symbol: 'Re', name: 'Rhenium',
    mass: 186.21, category: 'transition-metal',
    row: 6, col: 7,
    electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²',
    electronegativity: 1.9,
    density: 21.02,
    meltingPoint: 3186,
    boilingPoint: 5596,
    yearDiscovered: 1925,
    discoveredBy: 'Masataka Ogawa',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 13, 2],
    summary: 'Rhenium is one of the rarest elements in Earth\'s crust. It has an extremely high melting point and is used in jet engine superalloys and catalysts.',
    funFact: 'Rhenium was the last stable element to be discovered (1925) and is named after the Rhine River.'
  },
  {
    number: 76, symbol: 'Os', name: 'Osmium',
    mass: 190.23, category: 'transition-metal',
    row: 6, col: 8,
    electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²',
    electronegativity: 2.2,
    density: 22.59,
    meltingPoint: 3033,
    boilingPoint: 5012,
    yearDiscovered: 1803,
    discoveredBy: 'Smithson Tennant',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 14, 2],
    summary: 'Osmium is the densest naturally occurring element. It is a hard, brittle, bluish-white transition metal used in fountain pen nibs and specialized alloys.',
    funFact: 'Osmium is the densest element — a cube of osmium the size of a sugar cube weighs about 1.4 pounds.'
  },
  {
    number: 77, symbol: 'Ir', name: 'Iridium',
    mass: 192.22, category: 'transition-metal',
    row: 6, col: 9,
    electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²',
    electronegativity: 2.20,
    density: 22.56,
    meltingPoint: 2466,
    boilingPoint: 4428,
    yearDiscovered: 1803,
    discoveredBy: 'Smithson Tennant',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 15, 2],
    summary: 'Iridium is one of the most corrosion-resistant metals known. It is extremely dense and rare, used in spark plugs, crucibles, and the international kilogram standard.',
    funFact: 'A thin layer of iridium in rock strata worldwide is key evidence for the asteroid impact that killed the dinosaurs.'
  },
  {
    number: 78, symbol: 'Pt', name: 'Platinum',
    mass: 195.08, category: 'transition-metal',
    row: 6, col: 10,
    electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹',
    electronegativity: 2.28,
    density: 21.46,
    meltingPoint: 1768.3,
    boilingPoint: 3825,
    yearDiscovered: 1735,
    discoveredBy: 'Antonio de Ulloa',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 17, 1],
    summary: 'Platinum is a dense, malleable, highly unreactive precious metal. It is vital for catalytic converters, jewelry, laboratory equipment, and cancer treatment drugs.',
    funFact: 'All the platinum ever mined would fit in a cube roughly 25 feet on each side.'
  },
  {
    number: 79, symbol: 'Au', name: 'Gold',
    mass: 196.97, category: 'transition-metal',
    row: 6, col: 11,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
    electronegativity: 2.54,
    density: 19.282,
    meltingPoint: 1064.18,
    boilingPoint: 2856,
    yearDiscovered: -6000,
    discoveredBy: 'Ancient',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 18, 1],
    summary: 'Gold is a bright, slightly orange-yellow, dense, soft, malleable metal. It has been a valuable and highly sought-after precious metal throughout human history.',
    funFact: 'All the gold ever mined in human history would fill about three Olympic swimming pools.'
  },
  {
    number: 80, symbol: 'Hg', name: 'Mercury',
    mass: 200.59, category: 'transition-metal',
    row: 6, col: 12,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²',
    electronegativity: 2.00,
    density: 13.5336,
    meltingPoint: -38.83,
    boilingPoint: 356.73,
    yearDiscovered: -2000,
    discoveredBy: 'Ancient',
    phase: 'Liquid',
    shells: [2, 8, 18, 32, 18, 2],
    summary: 'Mercury is the only metallic element that is liquid at standard conditions. Known as "quicksilver," it has been used in thermometers, barometers, and fluorescent lighting.',
    funFact: 'Mercury is so dense that cannonballs can float on its surface.'
  },
  {
    number: 81, symbol: 'Tl', name: 'Thallium',
    mass: 204.38, category: 'post-transition-metal',
    row: 6, col: 13,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹',
    electronegativity: 1.62,
    density: 11.85,
    meltingPoint: 304,
    boilingPoint: 1473,
    yearDiscovered: 1861,
    discoveredBy: 'William Crookes',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 18, 3],
    summary: 'Thallium is a soft gray metal that was formerly used in rat poisons and insecticides. It is highly toxic and now used mainly in electronics and medical imaging.',
    funFact: 'Thallium was called "the poisoner\'s poison" because its salts are colorless, odorless, and tasteless.'
  },
  {
    number: 82, symbol: 'Pb', name: 'Lead',
    mass: 207.2, category: 'post-transition-metal',
    row: 6, col: 14,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²',
    electronegativity: 1.87,
    density: 11.342,
    meltingPoint: 327.46,
    boilingPoint: 1749,
    yearDiscovered: -7000,
    discoveredBy: 'Ancient',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 18, 4],
    summary: 'Lead is a heavy metal that has been used since ancient times. While toxic, it is still used in car batteries, radiation shielding, and ammunition.',
    funFact: 'Some historians believe lead poisoning from water pipes and wine sweeteners contributed to the fall of the Roman Empire.'
  },
  {
    number: 83, symbol: 'Bi', name: 'Bismuth',
    mass: 208.98, category: 'post-transition-metal',
    row: 6, col: 15,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³',
    electronegativity: 2.02,
    density: 9.807,
    meltingPoint: 271.5,
    boilingPoint: 1564,
    yearDiscovered: 1753,
    discoveredBy: 'Claude François Geoffroy',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 18, 5],
    summary: 'Bismuth is a pentavalent post-transition metal that forms beautiful rainbow-colored crystals. It is non-toxic and used in cosmetics and medicine (Pepto-Bismol).',
    funFact: 'Bismuth crystals display stunning iridescent rainbow colors due to thin oxide layers on their surface.'
  },
  {
    number: 84, symbol: 'Po', name: 'Polonium',
    mass: '(209)', category: 'post-transition-metal',
    row: 6, col: 16,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴',
    electronegativity: 2.0,
    density: 9.32,
    meltingPoint: 254,
    boilingPoint: 962,
    yearDiscovered: 1898,
    discoveredBy: 'Marie Curie',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 18, 6],
    summary: 'Polonium is a rare, highly radioactive metal discovered by Marie and Pierre Curie. It is one of the most dangerous substances known and has very few practical applications.',
    funFact: 'Marie Curie named polonium after her homeland Poland, which did not exist as an independent country at the time.'
  },
  {
    number: 85, symbol: 'At', name: 'Astatine',
    mass: '(210)', category: 'halogen',
    row: 6, col: 17,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵',
    electronegativity: 2.2,
    density: 7,
    meltingPoint: 302,
    boilingPoint: 337,
    yearDiscovered: 1940,
    discoveredBy: 'Dale R. Corson',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 18, 7],
    summary: 'Astatine is the rarest naturally occurring element on Earth, with at most 25 grams existing at any one time. It is radioactive and has very limited uses.',
    funFact: 'There is less than 1 ounce of astatine in the entire Earth\'s crust at any given time — making it the rarest natural element.'
  },
  {
    number: 86, symbol: 'Rn', name: 'Radon',
    mass: '(222)', category: 'noble-gas',
    row: 6, col: 18,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶',
    electronegativity: 2.2,
    density: 0.00973,
    meltingPoint: -71,
    boilingPoint: -61.7,
    yearDiscovered: 1900,
    discoveredBy: 'Friedrich Ernst Dorn',
    phase: 'Gas',
    shells: [2, 8, 18, 32, 18, 8],
    summary: 'Radon is a colorless, odorless, radioactive noble gas formed from the decay of radium. It can accumulate in buildings and is the second leading cause of lung cancer.',
    funFact: 'Radon is the leading cause of lung cancer among non-smokers and the second leading cause overall.'
  },
  // ═══════════════════════ Period 7 ═══════════════════════
  {
    number: 87, symbol: 'Fr', name: 'Francium',
    mass: '(223)', category: 'alkali-metal',
    row: 7, col: 1,
    electronConfig: '[Rn] 7s¹',
    electronegativity: 0.7,
    density: 1.87,
    meltingPoint: 27,
    boilingPoint: 677,
    yearDiscovered: 1939,
    discoveredBy: 'Marguerite Perey',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 18, 8, 1],
    summary: 'Francium is an extremely rare, highly radioactive alkali metal. It is the second rarest naturally occurring element and has no commercial applications.',
    funFact: 'Francium is so radioactive and rare that it has never been seen in bulk — at most a few hundred thousand atoms have existed at once.'
  },
  {
    number: 88, symbol: 'Ra', name: 'Radium',
    mass: '(226)', category: 'alkaline-earth-metal',
    row: 7, col: 2,
    electronConfig: '[Rn] 7s²',
    electronegativity: 0.9,
    density: 5.5,
    meltingPoint: 700,
    boilingPoint: 1737,
    yearDiscovered: 1898,
    discoveredBy: 'Marie Curie',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 18, 8, 2],
    summary: 'Radium is a highly radioactive alkaline earth metal that glows faintly blue. It was once used in self-luminous paint for watch dials and instrument panels.',
    funFact: 'Radium girls — factory workers who painted watch dials with radium paint — helped establish occupational safety standards.'
  },
  // Actinides (89–103) — shown in row 9
  {
    number: 89, symbol: 'Ac', name: 'Actinium',
    mass: '(227)', category: 'actinide',
    row: 9, col: 3,
    electronConfig: '[Rn] 6d¹ 7s²',
    electronegativity: 1.1,
    density: 10.07,
    meltingPoint: 1050,
    boilingPoint: 3198,
    yearDiscovered: 1899,
    discoveredBy: 'André-Louis Debierne',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 18, 9, 2],
    summary: 'Actinium is a radioactive element that gives the actinide series its name. It glows blue in the dark due to its intense radioactivity.',
    funFact: 'Actinium is about 150 times more radioactive than radium.'
  },
  {
    number: 90, symbol: 'Th', name: 'Thorium',
    mass: 232.04, category: 'actinide',
    row: 9, col: 4,
    electronConfig: '[Rn] 6d² 7s²',
    electronegativity: 1.3,
    density: 11.72,
    meltingPoint: 1750,
    boilingPoint: 4788,
    yearDiscovered: 1829,
    discoveredBy: 'Jöns Jacob Berzelius',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 18, 10, 2],
    summary: 'Thorium is a weakly radioactive metallic element. It could potentially fuel nuclear reactors more safely than uranium, producing less long-lived waste.',
    funFact: 'Thorium is named after Thor, the Norse god of thunder.'
  },
  {
    number: 91, symbol: 'Pa', name: 'Protactinium',
    mass: 231.04, category: 'actinide',
    row: 9, col: 5,
    electronConfig: '[Rn] 5f² 6d¹ 7s²',
    electronegativity: 1.5,
    density: 15.37,
    meltingPoint: 1572,
    boilingPoint: 4000,
    yearDiscovered: 1913,
    discoveredBy: 'Kasimir Fajans',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 20, 9, 2],
    summary: 'Protactinium is a dense, silvery-gray radioactive metal. It is one of the rarest and most expensive naturally occurring elements.',
    funFact: 'In 1961, the UK Atomic Energy Authority produced 125 grams of protactinium at a cost equivalent to about $500,000.'
  },
  {
    number: 92, symbol: 'U', name: 'Uranium',
    mass: 238.03, category: 'actinide',
    row: 9, col: 6,
    electronConfig: '[Rn] 5f³ 6d¹ 7s²',
    electronegativity: 1.38,
    density: 18.95,
    meltingPoint: 1135,
    boilingPoint: 4131,
    yearDiscovered: 1789,
    discoveredBy: 'Martin Heinrich Klaproth',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 21, 9, 2],
    summary: 'Uranium is a silvery-grey radioactive metal used as fuel in nuclear reactors and in nuclear weapons. It is the heaviest naturally occurring element.',
    funFact: 'A single fuel pellet of uranium the size of a pencil eraser contains as much energy as 17,000 cubic feet of natural gas.'
  },
  {
    number: 93, symbol: 'Np', name: 'Neptunium',
    mass: '(237)', category: 'actinide',
    row: 9, col: 7,
    electronConfig: '[Rn] 5f⁴ 6d¹ 7s²',
    electronegativity: 1.36,
    density: 20.45,
    meltingPoint: 644,
    boilingPoint: 3902,
    yearDiscovered: 1940,
    discoveredBy: 'Edwin McMillan',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 22, 9, 2],
    summary: 'Neptunium is a radioactive actinide metal named after the planet Neptune. It is produced as a by-product in nuclear reactors.',
    funFact: 'Neptunium was the first transuranium element discovered, named after Neptune, the next planet after Uranus (like uranium).'
  },
  {
    number: 94, symbol: 'Pu', name: 'Plutonium',
    mass: '(244)', category: 'actinide',
    row: 9, col: 8,
    electronConfig: '[Rn] 5f⁶ 7s²',
    electronegativity: 1.28,
    density: 19.84,
    meltingPoint: 640,
    boilingPoint: 3228,
    yearDiscovered: 1940,
    discoveredBy: 'Glenn T. Seaborg',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 24, 8, 2],
    summary: 'Plutonium is a radioactive actinide metal used in nuclear weapons and as fuel for nuclear reactors and space missions. It has six allotropic forms.',
    funFact: 'NASA\'s Voyager spacecraft, launched in 1977, are still powered by plutonium-238 thermoelectric generators.'
  },
  {
    number: 95, symbol: 'Am', name: 'Americium',
    mass: '(243)', category: 'actinide',
    row: 9, col: 9,
    electronConfig: '[Rn] 5f⁷ 7s²',
    electronegativity: 1.3,
    density: 13.69,
    meltingPoint: 1176,
    boilingPoint: 2011,
    yearDiscovered: 1944,
    discoveredBy: 'Glenn T. Seaborg',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 25, 8, 2],
    summary: 'Americium is a synthetic radioactive element. Its most notable use is in household smoke detectors, where americium-241 ionizes air to detect smoke particles.',
    funFact: 'There\'s a tiny amount of americium-241 in most home smoke detectors — it\'s the most common transuranium element in daily life.'
  },
  {
    number: 96, symbol: 'Cm', name: 'Curium',
    mass: '(247)', category: 'actinide',
    row: 9, col: 10,
    electronConfig: '[Rn] 5f⁷ 6d¹ 7s²',
    electronegativity: 1.3,
    density: 13.51,
    meltingPoint: 1345,
    boilingPoint: 3110,
    yearDiscovered: 1944,
    discoveredBy: 'Glenn T. Seaborg',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 25, 9, 2],
    summary: 'Curium is a hard, dense, silvery radioactive metal named after Marie and Pierre Curie. It is used in some thermoelectric generators for space missions.',
    funFact: 'Mars rovers Spirit and Opportunity each carried curium-244 to analyze the composition of Martian rocks.'
  },
  {
    number: 97, symbol: 'Bk', name: 'Berkelium',
    mass: '(247)', category: 'actinide',
    row: 9, col: 11,
    electronConfig: '[Rn] 5f⁹ 7s²',
    electronegativity: 1.3,
    density: 14.79,
    meltingPoint: 1050,
    boilingPoint: 2627,
    yearDiscovered: 1949,
    discoveredBy: 'Stanley G. Thompson',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 27, 8, 2],
    summary: 'Berkelium is a synthetic radioactive element produced in very small quantities. It was first made at the University of California, Berkeley.',
    funFact: 'Only about 1 gram of berkelium has ever been produced in the United States.'
  },
  {
    number: 98, symbol: 'Cf', name: 'Californium',
    mass: '(251)', category: 'actinide',
    row: 9, col: 12,
    electronConfig: '[Rn] 5f¹⁰ 7s²',
    electronegativity: 1.3,
    density: 15.1,
    meltingPoint: 900,
    boilingPoint: 1472,
    yearDiscovered: 1950,
    discoveredBy: 'Stanley G. Thompson',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 28, 8, 2],
    summary: 'Californium is a radioactive element used as a portable neutron source for detecting gold and silver ores, landmines, and for starting nuclear reactors.',
    funFact: 'Californium-252 costs about $27 million per gram, making it one of the most expensive substances on Earth.'
  },
  {
    number: 99, symbol: 'Es', name: 'Einsteinium',
    mass: '(252)', category: 'actinide',
    row: 9, col: 13,
    electronConfig: '[Rn] 5f¹¹ 7s²',
    electronegativity: 1.3,
    density: 8.84,
    meltingPoint: 860,
    boilingPoint: 996,
    yearDiscovered: 1952,
    discoveredBy: 'Albert Ghiorso',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 29, 8, 2],
    summary: 'Einsteinium is a synthetic element first identified in the debris of the first hydrogen bomb test in 1952. It is named after Albert Einstein.',
    funFact: 'Einsteinium was discovered in the fallout of the first hydrogen bomb test — its existence was kept secret for several years.'
  },
  {
    number: 100, symbol: 'Fm', name: 'Fermium',
    mass: '(257)', category: 'actinide',
    row: 9, col: 14,
    electronConfig: '[Rn] 5f¹² 7s²',
    electronegativity: 1.3,
    density: 9.7,
    meltingPoint: 1527,
    boilingPoint: null,
    yearDiscovered: 1952,
    discoveredBy: 'Albert Ghiorso',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 30, 8, 2],
    summary: 'Fermium is a synthetic, highly radioactive element named after Enrico Fermi. Like einsteinium, it was first found in nuclear test debris.',
    funFact: 'Fermium is the heaviest element that can be produced by neutron bombardment of lighter elements.'
  },
  {
    number: 101, symbol: 'Md', name: 'Mendelevium',
    mass: '(258)', category: 'actinide',
    row: 9, col: 15,
    electronConfig: '[Rn] 5f¹³ 7s²',
    electronegativity: 1.3,
    density: 10.3,
    meltingPoint: 827,
    boilingPoint: null,
    yearDiscovered: 1955,
    discoveredBy: 'Albert Ghiorso',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 31, 8, 2],
    summary: 'Mendelevium is a synthetic element named after Dmitri Mendeleev, the creator of the periodic table. Only tiny quantities have ever been produced.',
    funFact: 'Mendelevium was the first element to be identified one atom at a time.'
  },
  {
    number: 102, symbol: 'No', name: 'Nobelium',
    mass: '(259)', category: 'actinide',
    row: 9, col: 16,
    electronConfig: '[Rn] 5f¹⁴ 7s²',
    electronegativity: 1.3,
    density: 9.9,
    meltingPoint: 827,
    boilingPoint: null,
    yearDiscovered: 1966,
    discoveredBy: 'Georgy Flyorov',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 8, 2],
    summary: 'Nobelium is a synthetic, highly radioactive element named after Alfred Nobel. It has no practical applications outside of scientific research.',
    funFact: 'Nobelium\'s discovery was claimed by three different groups in three different countries.'
  },
  {
    number: 103, symbol: 'Lr', name: 'Lawrencium',
    mass: '(266)', category: 'actinide',
    row: 9, col: 17,
    electronConfig: '[Rn] 5f¹⁴ 7s² 7p¹',
    electronegativity: 1.3,
    density: 14.4,
    meltingPoint: 1627,
    boilingPoint: null,
    yearDiscovered: 1961,
    discoveredBy: 'Albert Ghiorso',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 8, 3],
    summary: 'Lawrencium is a synthetic element named after Ernest O. Lawrence, inventor of the cyclotron. It is the final member of the actinide series.',
    funFact: 'Lawrencium was the last actinide to be synthesized and closes out the f-block of the periodic table.'
  },
  // Continue Period 7 after actinides
  {
    number: 104, symbol: 'Rf', name: 'Rutherfordium',
    mass: '(267)', category: 'transition-metal',
    row: 7, col: 4,
    electronConfig: '[Rn] 5f¹⁴ 6d² 7s²',
    electronegativity: null,
    density: 23.2,
    meltingPoint: 2100,
    boilingPoint: 5500,
    yearDiscovered: 1969,
    discoveredBy: 'Albert Ghiorso',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 10, 2],
    summary: 'Rutherfordium is a synthetic, highly radioactive element named after Ernest Rutherford. It was the subject of a naming controversy between American and Soviet scientists.',
    funFact: 'Rutherfordium atoms exist for only a few seconds before decaying.'
  },
  {
    number: 105, symbol: 'Db', name: 'Dubnium',
    mass: '(268)', category: 'transition-metal',
    row: 7, col: 5,
    electronConfig: '[Rn] 5f¹⁴ 6d³ 7s²',
    electronegativity: null,
    density: 29.3,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1970,
    discoveredBy: 'Albert Ghiorso',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 11, 2],
    summary: 'Dubnium is a synthetic element named after the Russian town of Dubna. It has no practical applications and can only be produced in particle accelerators.',
    funFact: 'Dubnium was part of the "Transfermium Wars" — a decades-long dispute between labs over who got to name elements.'
  },
  {
    number: 106, symbol: 'Sg', name: 'Seaborgium',
    mass: '(269)', category: 'transition-metal',
    row: 7, col: 6,
    electronConfig: '[Rn] 5f¹⁴ 6d⁴ 7s²',
    electronegativity: null,
    density: 35.0,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1974,
    discoveredBy: 'Albert Ghiorso',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 12, 2],
    summary: 'Seaborgium is a synthetic element named after Glenn T. Seaborg, the only element named after a living person at the time of naming.',
    funFact: 'Glenn Seaborg was the only person who could write his address in chemical elements: Sg, Lr, Bk, Cf, Am (Seaborgium, Lawrencium, Berkelium, Californium, Americium).'
  },
  {
    number: 107, symbol: 'Bh', name: 'Bohrium',
    mass: '(270)', category: 'transition-metal',
    row: 7, col: 7,
    electronConfig: '[Rn] 5f¹⁴ 6d⁵ 7s²',
    electronegativity: null,
    density: 37.1,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1981,
    discoveredBy: 'Peter Armbruster',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 13, 2],
    summary: 'Bohrium is a synthetic element named after Danish physicist Niels Bohr. Only a few atoms have ever been produced.',
    funFact: 'Bohrium atoms have been observed to have chemical properties similar to rhenium, as predicted by the periodic table.'
  },
  {
    number: 108, symbol: 'Hs', name: 'Hassium',
    mass: '(277)', category: 'transition-metal',
    row: 7, col: 8,
    electronConfig: '[Rn] 5f¹⁴ 6d⁶ 7s²',
    electronegativity: null,
    density: 40.7,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1984,
    discoveredBy: 'Peter Armbruster',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 14, 2],
    summary: 'Hassium is a synthetic element named after the German state of Hesse. Chemical experiments show it behaves like osmium, its lighter homolog.',
    funFact: 'Hassium is the heaviest element whose chemical properties have been experimentally confirmed.'
  },
  {
    number: 109, symbol: 'Mt', name: 'Meitnerium',
    mass: '(278)', category: 'unknown',
    row: 7, col: 9,
    electronConfig: '[Rn] 5f¹⁴ 6d⁷ 7s²',
    electronegativity: null,
    density: 37.4,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1982,
    discoveredBy: 'Peter Armbruster',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 15, 2],
    summary: 'Meitnerium is a synthetic element named after Lise Meitner, who helped discover nuclear fission. It has no practical applications.',
    funFact: 'Meitnerium honors Lise Meitner, who was repeatedly snubbed for the Nobel Prize despite her pivotal role in discovering nuclear fission.'
  },
  {
    number: 110, symbol: 'Ds', name: 'Darmstadtium',
    mass: '(281)', category: 'unknown',
    row: 7, col: 10,
    electronConfig: '[Rn] 5f¹⁴ 6d⁸ 7s²',
    electronegativity: null,
    density: 34.8,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1994,
    discoveredBy: 'Peter Armbruster',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 16, 2],
    summary: 'Darmstadtium is a synthetic element named after Darmstadt, Germany, where it was first created at the GSI Helmholtz Centre.',
    funFact: 'Darmstadtium is predicted to be a noble metal — but nobody has ever had enough atoms to check.'
  },
  {
    number: 111, symbol: 'Rg', name: 'Roentgenium',
    mass: '(282)', category: 'unknown',
    row: 7, col: 11,
    electronConfig: '[Rn] 5f¹⁴ 6d⁹ 7s²',
    electronegativity: null,
    density: 28.7,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1994,
    discoveredBy: 'Peter Armbruster',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 17, 2],
    summary: 'Roentgenium is a synthetic element named after Wilhelm Röntgen, discoverer of X-rays. It is expected to be a noble metal.',
    funFact: 'Roentgenium is in the same group as copper, silver, and gold — but we may never know if it shares their luster.'
  },
  {
    number: 112, symbol: 'Cn', name: 'Copernicium',
    mass: '(285)', category: 'unknown',
    row: 7, col: 12,
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s²',
    electronegativity: null,
    density: 23.7,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1996,
    discoveredBy: 'Sigurd Hofmann',
    phase: 'Liquid',
    shells: [2, 8, 18, 32, 32, 18, 2],
    summary: 'Copernicium is a synthetic element named after astronomer Nicolaus Copernicus. Theoretical predictions suggest it may be a gas or volatile liquid at room temperature.',
    funFact: 'Copernicium may behave more like a noble gas than a metal due to relativistic effects on its electrons.'
  },
  {
    number: 113, symbol: 'Nh', name: 'Nihonium',
    mass: '(286)', category: 'unknown',
    row: 7, col: 13,
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹',
    electronegativity: null,
    density: 16,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 2003,
    discoveredBy: 'Kosuke Morita',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 18, 3],
    summary: 'Nihonium is a synthetic element and the first to be discovered in Asia. Its name means "Japan" (Nihon in Japanese).',
    funFact: 'Nihonium was the first element discovered in an Asian country, a point of national pride for Japan.'
  },
  {
    number: 114, symbol: 'Fl', name: 'Flerovium',
    mass: '(289)', category: 'unknown',
    row: 7, col: 14,
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²',
    electronegativity: null,
    density: 14,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1999,
    discoveredBy: 'Joint Institute for Nuclear Research',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 18, 4],
    summary: 'Flerovium is a superheavy artificial element named after the Flerov Laboratory of Nuclear Reactions. It may have some noble gas character.',
    funFact: 'Flerovium is near a predicted "island of stability" where superheavy elements might have longer half-lives.'
  },
  {
    number: 115, symbol: 'Mc', name: 'Moscovium',
    mass: '(290)', category: 'unknown',
    row: 7, col: 15,
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³',
    electronegativity: null,
    density: 13.5,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 2003,
    discoveredBy: 'Joint Institute for Nuclear Research',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 18, 5],
    summary: 'Moscovium is a synthetic element named after Moscow Oblast. It is extremely radioactive and has no practical applications.',
    funFact: 'Moscovium gained pop culture fame when Bob Lazar claimed UFOs were powered by element 115 — decades before it was actually created.'
  },
  {
    number: 116, symbol: 'Lv', name: 'Livermorium',
    mass: '(293)', category: 'unknown',
    row: 7, col: 16,
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴',
    electronegativity: null,
    density: 12.9,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 2000,
    discoveredBy: 'Joint Institute for Nuclear Research',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 18, 6],
    summary: 'Livermorium is a synthetic superheavy element named after the Lawrence Livermore National Laboratory in California.',
    funFact: 'Livermorium atoms exist for only milliseconds before decaying into lighter elements.'
  },
  {
    number: 117, symbol: 'Ts', name: 'Tennessine',
    mass: '(294)', category: 'unknown',
    row: 7, col: 17,
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵',
    electronegativity: null,
    density: 7.2,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 2010,
    discoveredBy: 'Joint Institute for Nuclear Research',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 18, 7],
    summary: 'Tennessine is a synthetic superheavy element named after the state of Tennessee, home to Oak Ridge National Laboratory, Vanderbilt University, and the University of Tennessee.',
    funFact: 'Tennessine is the most recently named element, officially recognized by IUPAC in 2016.'
  },
  {
    number: 118, symbol: 'Og', name: 'Oganesson',
    mass: '(294)', category: 'unknown',
    row: 7, col: 18,
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶',
    electronegativity: null,
    density: 5.0,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 2006,
    discoveredBy: 'Joint Institute for Nuclear Research',
    phase: 'Solid',
    shells: [2, 8, 18, 32, 32, 18, 8],
    summary: 'Oganesson is the heaviest known element, named after nuclear physicist Yuri Oganessian. It is the only element named after a living person at the time.',
    funFact: 'Oganesson is in the noble gas column but may actually be a solid at room temperature due to relativistic effects.'
  },
];

// Placeholder positions for lanthanide/actinide indicators in the main table
const LANTHANIDE_PLACEHOLDER = { row: 6, col: 3, label: '57-71', sublabel: 'La-Lu', link: 'lanthanide' };
const ACTINIDE_PLACEHOLDER = { row: 7, col: 3, label: '89-103', sublabel: 'Ac-Lr', link: 'actinide' };
